GET http://localhost:3001/docente
##########

GET http://localhost:3001/docente/2
##########

POST http://localhost:3001/docente/
Content-Type: application/json

{
    "id": 3,
    "nombre": "Pedro",
    "apellido": "Gomez",
    "curso": "Arquitectura de datos"
}

###########

PUT http://localhost:3001/docente
Content-Type: application/json
{
    "id": ,
    "nombre": "Sandra Betty",
    "apellido": "Sanchez",
    "curso": "Derecho Penal"
}

#############
DELETE http://localhost:3001/docente/1

